[package]
name = "doco"

version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.86"
getset = "0.1.2"
testcontainers = "0.22.0"
typed-builder = "0.20.0"
