---
name: Example / axum

"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest

    outputs:
      any_changed: ${{ steps.detect-changes.outputs.any_changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Get changed files
        id: detect-changes
        uses: tj-actions/changed-files@v45
        with:
          files: |
            .github/workflows/axum.yml
            crates/**/*
            examples/axum-postgres/**/*

      - name: Print changed files
        run: |
          for file in ${{ steps.detect-changes.outputs.all_changed_files }}; do
            echo "$file"
          done

  format:
    name: Check Rust style
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.8

      - name: Run check with Earthly
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: earthly --ci --push --remote-cache=ghcr.io/otterbuild/doco-earthly-cache:example-axum-format +example-axum-format

  lint:
    name: Lint Rust code
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.8

      - name: Run check with Earthly
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: earthly --ci --push --remote-cache=ghcr.io/otterbuild/doco-earthly-cache:example-axum-lint +example-axum-lint

  test:
    name: Run Rust tests
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.8

      - name: Run check with Earthly
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: earthly --allow-privileged --push --remote-cache=ghcr.io/otterbuild/doco-earthly-cache:example-axum-test --strict +example-axum-test
