---
name: Continuous Integration

"on":
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  targets:
    name: Enumerate Just recipes
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.export-targets.outputs.targets }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Install Just
        uses: taiki-e/install-action@84f5ac3124727fb3d284d4d22ee9ab3654fd09a6 # v2
        with:
          tool: just
      - name: Export targets
        id: export-targets
        run: echo "targets=$(just --list | awk '/check-|format-|lint-|test-/{print $1}' | jq -cnR '[inputs]')" >> "$GITHUB_OUTPUT"

  checks:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: targets
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.targets.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Install Flox
        uses: flox/install-flox-action@1128abd73431089ab9d871c893b4e72a729354e1 # v2
      - name: Remove Flox installer (if it exists)
        run: rm -f flox.x86_64-linux.deb
      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
        with:
          prefix-key: "v0-${{ matrix.target }}"
          cache-on-failure: true
          cache-provider: "warpbuild"
      - name: Run check with Just
        uses: flox/activate-action@7065dcbe5583b7b015f07a8ebd49d7266e3053e8 # v1
        with:
          command: just ${{ matrix.target }}
      - name: Upload coverage report
        if: matrix.target == 'test-coverage'
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cobertura.xml

  success:
    name: All checks succeeded
    runs-on: ubuntu-latest
    permissions: {}
    needs: checks
    if: always()
    steps:
      - name: Check if all checks succeeded
        # zizmor: ignore[template-injection]
        run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
