---
name: Leptos

"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest

    outputs:
      any_changed: ${{ steps.detect-changes.outputs.any_changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: detect-changes
        uses: tj-actions/changed-files@v45
        with:
          files: |
            .github/workflows/leptos.yml
            examples/leptos/**/*.rs
            examples/leptos/**/*.toml

      - name: Print changed files
        run: |
          for file in ${{ steps.detect-changes.outputs.all_changed_files }}; do
            echo "$file"
          done

  build:
    name: Build Leptos example
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache build artifacts
        uses: swatinem/rust-cache@v2.7.3
        with:
          prefix-key: cargo-1.81.0
          cache-directories: ".bin"

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install cargo-run-bin
        run: cargo install cargo-run-bin

      - name: Install cargo binaries
        run: |
          cargo bin --install
          cargo bin --sync-aliases

      - name: Build the app
        working-directory: examples/leptos
        run: cargo leptos build

  style:
    name: Check Leptos style
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache build artifacts
        uses: swatinem/rust-cache@v2.7.3
        with:
          prefix-key: cargo-1.81.0
          cache-directories: ".bin"

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install cargo-run-bin
        run: cargo install cargo-run-bin

      - name: Install cargo binaries
        run: |
          cargo bin --install
          cargo bin --sync-aliases

      - name: Run formatters
        working-directory: examples/leptos
        run: cargo bin leptosfmt --check .

  test:
    name: Run Leptos tests
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache build artifacts
        uses: swatinem/rust-cache@v2.7.3
        with:
          prefix-key: cargo-1.81.0
          cache-directories: ".bin"

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install cargo-run-bin
        run: cargo install cargo-run-bin

      - name: Install cargo binaries
        run: |
          cargo bin --install
          cargo bin --sync-aliases

      - name: Run tests
        run: cargo test --all-features --all-targets
