---
name: Leptos

"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest

    outputs:
      any_changed: ${{ steps.detect-changes.outputs.any_changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: detect-changes
        uses: tj-actions/changed-files@v45
        with:
          files: |
            .github/workflows/leptos.yml
            examples/leptos/**/*.rs
            examples/leptos/**/*.toml
            examples/leptos/Dockerfile

      - name: Print changed files
        run: |
          for file in ${{ steps.detect-changes.outputs.all_changed_files }}; do
            echo "$file"
          done

  test:
    name: Run Leptos tests
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache build artifacts
        uses: swatinem/rust-cache@v2.7.3
        with:
          prefix-key: leptos-1.81.0
          cache-directories: ".bin"
          workspaces: examples/leptos -> target

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install cargo-run-bin
        working-directory: examples/leptos
        run: cargo install cargo-run-bin

      - name: Install cargo binaries
        working-directory: examples/leptos
        run: |
          cargo bin --install
          cargo bin --sync-aliases

      - name: Build Docker image for Leptos app
        uses: docker/build-push-action@v6
        with:
          context: .
          file: examples/leptos/Dockerfile
          load: true
          tags: doco:leptos
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests
        working-directory: examples/leptos
        run: cargo test --all-features --all-targets
