---
name: Rust

"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest

    outputs:
      any_changed: ${{ steps.detect-changes.outputs.any_changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: detect-changes
        uses: tj-actions/changed-files@v45
        with:
          files: |
            .github/workflows/rust.yml
            **/*.rs
            **/*.toml

      - name: Print changed files
        run: |
          for file in ${{ steps.detect-changes.outputs.all_changed_files }}; do
            echo "$file"
          done

  lint:
    name: Lint Rust code
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache build artifacts
        uses: swatinem/rust-cache@v2.7.3
        with:
          prefix-key: cargo-1.80.1

      - name: Run Clippy
        run: cargo clippy --all-features --all-targets -- -D warnings

  style:
    name: Check Rust style
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache build artifacts
        uses: swatinem/rust-cache@v2.7.3
        with:
          prefix-key: cargo-1.80.1

      - name: Run rustfmt
        run: cargo fmt --check

  test:
    name: Run Rust tests
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache build artifacts
        uses: swatinem/rust-cache@v2.7.3
        with:
          prefix-key: cargo-1.80.1

      - name: Run tests
        run: cargo test --all-features --all-targets
