---
name: Rust

"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest

    outputs:
      any_changed: ${{ steps.detect-changes.outputs.any_changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: detect-changes
        uses: tj-actions/changed-files@v46
        with:
          files: |
            .github/workflows/rust.yml
            **/*.rs
            **/*.toml
            !examples/**

      - name: Print changed files
        run: |
          for file in ${{ steps.detect-changes.outputs.all_changed_files }}; do
            echo "$file"
          done

  deps-latest:
    name: Test latest versions
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.8

      - name: Run tests with latest dependency versions
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: earthly --ci --push --remote-cache=ghcr.io/otterbuild/doco-earthly-cache:rust-deps-latest +rust-deps-latest

  deps-minimal:
    name: Test minimal dependencies
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.8

      - name: Run check with Earthly
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: earthly --ci --push --remote-cache=ghcr.io/otterbuild/doco-earthly-cache:rust-deps-minimal +rust-deps-minimal

  doc:
    name: Compile documentation
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.8

      - name: Run check with Earthly
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: earthly --ci --push --remote-cache=ghcr.io/otterbuild/doco-earthly-cache:rust-doc +rust-doc

  features:
    name: Test features
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.8

      - name: Run check with Earthly
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: earthly --ci --push --remote-cache=ghcr.io/otterbuild/doco-earthly-cache:rust-features +rust-features

  format:
    name: Check Rust style
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.8

      - name: Run check with Earthly
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: earthly --ci --push --remote-cache=ghcr.io/otterbuild/doco-earthly-cache:rust-format +rust-format

  lint:
    name: Lint Rust code
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.8

      - name: Run check with Earthly
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: earthly --ci --push --remote-cache=ghcr.io/otterbuild/doco-earthly-cache:rust-lint +rust-lint

  test:
    name: Run Rust tests
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.8

      - name: Run tests with test coverage
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: earthly --allow-privileged --push --remote-cache=ghcr.io/otterbuild/doco-earthly-cache:rust-test --strict +rust-test --SAVE_REPORT=yes

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: cobertura.xml
